import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from './providers'
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html >
      <body>
        {/* Layout UI */}
         <Providers>{children}</Providers>
      </body>
    </html>
  )
}
